apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: media
  namespace: argocd # Must match where Argo CD is installed
  # finalizers:
  # - resources-finalizer.argocd.argoproj.io # Ensures apps/resources are deleted when project is deleted
spec:
  description: Media apps project
  # Allow manifests to deploy from any Git repos. Use specific URLs for compliance.
  sourceRepos:
  - '*'
  # Only permit applications to deploy to specific namespaces and clusters
  destinations:
  - namespace: argocd
    server: https://kubernetes.default.svc # The in-cluster Kubernetes API server
  - namespace: media
    server: https://kubernetes.default.svc # The in-cluster Kubernetes API server
  - namespace: reaper
    server: https://kubernetes.default.svc # The in-cluster Kubernetes API server
  - namespace: utilities
    server: https://kubernetes.default.svc # The in-cluster Kubernetes API server

  # Define roles and RBAC policies here (optional)
  # roles:
  #   - name: custom-project-role
  #     description: Role with limited application access
  #     policies:
  #       - p, proj:my-project:custom-project-role, applications, get, my-app/*, allow