apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-base
  namespace: argocd
  finalizers:
    # The default behaviour is foreground cascading deletion
    - resources-finalizer.argocd.argoproj.io
spec:
  project: system
  source:
    repoURL: 'git@github.com:pirish/cluster-base.git'
    path: apps_system # Directory containing child application manifests
    targetRevision: HEAD
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd # Or another namespace where you want the parent app to reside
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true