apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trust-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  project: system
  sources:
  - chart: trust-manager
    repoURL: oci://quay.io/jetstack/charts/trust-manager
    path: .
    targetRevision: v0.24.0
    helm:
      releaseName: trust-manager
      valueFiles:
        - $values/apps_system/trust-manager/values.yaml
  - repoURL: 'git@github.com:pirish/cluster-base.git'
    targetRevision: HEAD
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
